services:
  echo-daemon-server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "50999:50999"
    volumes: 
      - ./data:/app/data
      - ./temp:/app/temp
      - ./settings.yaml:/app/config/config.yaml
      - "${MUSIC_ROOT}:/app/music:ro"
